name: Build and Deploy WASM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      # Install just
      - name: Install just
        run: cargo install just --locked

      # Install needed tools
      - name: Install tools
        run: just install-tools
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      # Build Rust -> Wasm
      - name: Build project
        run: just build-wasm

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pkg

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4      
